baseURL = "/"
languageCode = "en-us"
title = "Evolve"
theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
	  
[params]
editURL = ""
description = "Evolve documentation cross platform database migration tool"
author = "Philippe Lécaillon"
themeVariant = "evolve"
ordersectionsby = "weight"
disableShortcutsTitle = true
disableBreadcrumb = true
disableLanguageSwitchingButton = true
disableMermaid = true
googleAnalytics = "UA-115057388-1"

[[Languages.en.menu.shortcuts]]
name = "<i class='far fa-heart' style='color:HotPink'></i> Sponsor"
url = "https://github.com/sponsors/lecaillon"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-envelope-open'></i> Contact"
url = "mailto:evolve-db@hotmail.com"
weight = 20

[[Languages.en.menu.shortcuts]] 
name = "<i class='fab fa-twitter'></i> Twitter"
identifier = "tw"
url = "https://twitter.com/evolve_db"
weight = 30

[[Languages.en.menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/lecaillon/Evolve"
weight = 40
